project:
  type: book
  output-dir: docs

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Flora Unveiled: Exploring the Diverse Plant Collections of Berlin's Botanical Garden and Museum"
  author: "Lisa Sommer"
  date: "2023-07-06"
  # this section determines which files will be added to the book as chapters
  chapters:
    - index.qmd
    - colophon.ipynb
    - collection003.qmd
    #- paintings_1ls.ipynb
    - plants_1ls.ipynb
    - collection-sommer.ipynb
    
    
  repo-url: https://github.com/Pgxe9zu1/catalogue-003
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: 6780765/Ranunculus seguieri.png

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: true

format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at https://quarto.org/docs/output-formats/html-themes.html
    theme: lux
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  pdf:
    documentclass: book
  docx: 
    toc: true
  epub: 
    toc: true  